name: Docker

on:
  push:
    branches:
      - master

  # Run every day 2 AM
  schedule:
    - cron:  '* 2 * * *'

env:
  IMAGE_NAME: counterstrikesource-server
  CR_PAT: ${{ secrets.CR_PAT }}

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "$CR_PAT" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker inspect --format='{{.Created}}' ghcr.io/lanofdoom/counterstrikesource-base/counterstrikesource-base:latest > counterstrikesource-base.ver
          docker run --entrypoint=/bin/dpkg $IMAGE_NAME -l > packages.ver
          docker run --entrypoint=/bin/find $IMAGE_NAME /opt/game -type f -exec sha256sum {} \; > cstrike.ver

          if cmp -s packages.ver deps/packages.ver \
             && cmp -s counterstrikesource-base.ver deps/counterstrikesource-base.ver \
             && cmp -s cstrike.ver deps/cstrike.ver ; \
          then exit ; \
          fi

          mkdir -p deps
          cp packages.ver deps/packages.ver
          cp counterstrikesource-base.ver deps/counterstrikesource-base.ver
          cp cstrike.ver deps/cstrike.ver

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Update dependency versions
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: deps
          TARGET_FOLDER: deps